### ISSUE TITLE
i Followed your blog! nice one 

### ISSUE THREAD

**Issue by Kampouse** [phip1611/qemu-debugcon-linux-driver#6]
Hey threre i seen your blog i wanted to say nice job of showing this i love it! but there one thing that would have like to see that is missing.  
How to you run the expression that is written in the build_kmod_.nix!
thanks you !

**Comment by phip1611** [comment]
Hey! Thank you! Can you please provide some more details? There is no `build_kmod.nix` in this repo, but `debugcon_module.nix`, do you mean that?

You can build the kernel-module either using:

```bash
$ nix-build -E '
let
  pkgs = import <nixpkgs> {};
in
pkgs.callPackage nix/debugcon_module.nix { kernel = pkgs.linux_latest; }
'
``` 

or by just running

`$ nix-build -A debugconModule`

**Comment by Kampouse** [comment]
thanks you!
